server:
  port: 8800

spring:
  application:
    name: one
  profiles:
    active: dev
  main:
    allow-circular-references: true
  datasource:
    druid:
      driver-class-name: ${one.datasource.driver-class-name}
      url: jdbc:mysql://${one.datasource.host}:${one.datasource.port}/${one.datasource.database}?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
      username: ${one.datasource.username}
      password: ${one.datasource.password}
  redis:
    host: ${one.redis.host}
    port: ${one.redis.port}
    password: ${one.redis.password}
    database: ${one.redis.database}
    timeout: 5000 # 连接超时时间(毫秒)
    lettuce:
      pool:
        max-active: 8 # 连接池最大连接数(使用负值表示没有限制)
        max-wait: -1 # 连接池最大阻塞等待时间(使用负值表示没有限制)
        max-idle: 8 # 连接池中的最大空闲连接
        min-idle: 0 # 连接池中的最小空闲连接

mybatis-plus:
  #mapper配置文件
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.one.po
  configuration:
    #开启驼峰命名
    map-underscore-to-camel-case: true
    # log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      id-type: ASSIGN_ID

logging:
  level:
    com:
      example:
        mapper: debug
        service: info
        controller: info

one:
  jwt:
    # 设置jwt签名加密时使用的秘钥
    admin-secret-key: 68ee1e72bf52d13bc471e8a1dc4ae746
    # 设置jwt过期时间
    admin-ttl: 7200000
    # 设置前端传递过来的令牌名称
    admin-token-name: token
    user-secret-key: itheima
    user-ttl: 7200000
    user-token-name: authentication